export const LOBBY_STATE = 'LOBBY_STATE';
export const STARTING_STATE = 'STARTING_STATE';
export const DRAWING_STATE = 'DRAWING_STATE';
export const DISPLAY_STATE = 'DISPLAY_STATE';
export const VOTING_STATE = 'VOTING_STATE';
export const END_ROUND_STATE = "END_ROUND_STATE";
export const END_GAME_STATE = 'END_GAME_STATE';